### ISSUE TITLE
Naming stills and merging CoralNet with telemetry files 

### ISSUE THREAD

**Issue by m-h-williams** [zhrandell/Seattle_Aquarium_ROV_telemetry_imagery_analysis#4]
I was unable to name extracted stills based on the running time of a flight that would change minutes and seconds. Instead, I adjusted the python script to write image names as 'Date_Time_FlightSeconds.jpg' (ex: 2022_08_15_10-01-31_120.jpg) where FlightSeconds will be the running flight time in seconds. 

An example of the how the image name is written in python is below. Note everything after the last '/ ' is what becomes the image name. 
https://github.com/zhrandell/Seattle_Aquarium_ROV_telemetry_imagery_analysis/blob/e0213dffbd64c8c645029347f2579986a638c308/code/4k_to_still.py#L15

To merge CoralNet and telemetry data, the names of the images within CoralNet need to match the rows of the telemetry file the images correspond to. To do that, I created a new column within the telemetry file that would match the naming format from the python still extraction script (i.e.  Date_Time_FlightSeconds.jpg). I then merged CoralNet and telemetry rows based on the image name. The entire script for that process is below. 

https://github.com/zhrandell/Seattle_Aquarium_ROV_telemetry_imagery_analysis/blob/e0213dffbd64c8c645029347f2579986a638c308/code/Telemetry_CoralNet.R

**Comment by zhrandell** [comment]
This looks great! Thank you, @m-h-williams
